In [34]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

In [9]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [78]:
data_frame = pd.read_csv('train.csv')
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1421 entries, 0 to 1420
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Gender      1421 non-null   int64  
 1   Hemoglobin  1421 non-null   float64
 2   MCH         1421 non-null   float64
 3   MCHC        1421 non-null   float64
 4   MCV         1421 non-null   float64
 5   Result      1421 non-null   int64  
dtypes: float64(4), int64(2)
memory usage: 66.7 KB


In [87]:
X = data_frame.iloc[:,:-1].values
y = data_frame.iloc[:,-1].values
print(X)
print(y)

[[ 1.  14.9 22.7 29.1 83.7]
 [ 0.  15.9 25.4 28.3 72. ]
 [ 0.   9.  21.5 29.6 71.2]
 ...
 [ 1.  13.1 17.7 28.1 80.7]
 [ 0.  14.3 16.2 29.5 95.2]
 [ 0.  11.8 21.2 28.4 98.1]]

[0 0 1 ... 1 0 1]


In [41]:
convert = preprocessing.MinMaxScaler()
X = convert.fit_transform(X)
print(X)

[[1.         0.80582524 0.47857143 0.27659574 0.44409938]
 [0.         0.90291262 0.67142857 0.10638298 0.08074534]
 [0.         0.23300971 0.39285714 0.38297872 0.05590062]
 ...
 [1.         0.63106796 0.12142857 0.06382979 0.35093168]
 [0.         0.74757282 0.01428571 0.36170213 0.80124224]
 [0.         0.50485437 0.37142857 0.12765957 0.89130435]]


In [42]:
np.random.seed(42)
xtrain, xtest, ytrain, ytest = train_test_split(X,y,test_size = 0.2)

In [80]:
print('Dữ liệu huấn luyện')
print(xtrain)
print()
print(ytrain)

Dữ liệu huấn luyện
[[0.         0.59223301 0.52142857 0.53191489 0.72670807]
 [1.         0.36893204 0.20714286 0.         0.17701863]
 [1.         0.81553398 0.34285714 0.95744681 0.59937888]
 ...
 [0.         0.66019417 0.66428571 0.17021277 0.44720497]
 [0.         0.40776699 0.26428571 0.36170213 0.73291925]
 [0.         0.97087379 0.40714286 0.63829787 0.58074534]]

[0 1 0 ... 0 1 0]


In [85]:
print('Dữ liệu thử nghiệm ban đầu')
print(xtest)
print(ytest)

Dữ liệu thử nghiệm ban đầu
[[1.         0.59223301 0.22142857 0.42553191 0.46273292]
 [0.         0.7961165  0.87142857 0.63829787 0.04037267]
 [1.         0.66990291 0.83571429 0.68085106 0.24534161]
 ...
 [1.         0.53398058 0.20714286 0.72340426 0.20496894]
 [0.         0.6407767  0.3        0.14893617 0.49068323]
 [1.         0.37864078 0.87857143 0.19148936 0.95341615]]

[1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 0 1
 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 0 0 0
 0 0 0 1 0 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0 1 0 1
 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 1
 1 1 0 1 0 0 1 1 0 1 1 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 1 1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0
 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1
 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 1]


In [84]:
model = GaussianNB()
model.fit(xtrain,ytrain)
ypred = model.predict(xtest)
print(ypred)

[1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 0 1
 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0
 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 0 1 0 1
 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1
 1 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 0 1 0 0 1 0 0 1 0 0
 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0
 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1
 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 1]


In [59]:
cm = confusion_matrix(ytest,ypred)
print("Confushion Matrix")
print(cm)
print(f'\nTrue Positives (TP):   {cm[0,0]}')
print(f'False Positives (FP):  {cm[0,1]}')
print(f'False Negatives (FN):  {cm[1,0]}')
print(f'True Negatives (TN):   {cm[1,1]}')

Confushion Matrix
[[150   7]
 [  7 121]]

True Positives (TP):   150
False Positives (FP):  7
False Negatives (FN):  7
True Negatives (TN):   121


In [49]:
print(accuracy_score(ytest,ypred))

0.9508771929824561


In [60]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv


In [68]:
data_test = pd.read_csv('test.csv')
X_data_test = data_test.iloc[:5, :-1].values
print(X_data_test)

[[ 0.  15.2 21.9 29.6 69.5]
 [ 1.  13.4 17.7 31.6 97.2]
 [ 1.  15.9 22.4 28.9 93. ]
 [ 1.  12.1 25.9 29.3 82.6]
 [ 0.  14.5 24.2 27.9 71.7]]


In [70]:
y_data_test = data_test.iloc[:5, -1].values
print(y_data_test)

[0 1 0 1 0]


In [72]:
replace = preprocessing.MinMaxScaler()
X_data_test = replace.fit_transform(X_data_test)
print(X_data_test)

[[0.         0.81578947 0.51219512 0.45945946 0.        ]
 [1.         0.34210526 0.         1.         1.        ]
 [1.         1.         0.57317073 0.27027027 0.84837545]
 [1.         0.         1.         0.37837838 0.47292419]
 [0.         0.63157895 0.79268293 0.         0.07942238]]


In [77]:
predictions_test = model.predict(X_data_test)
print('Dự đoán dữ liệu trên test')
for i, prediction in enumerate(predictions_test):
  print(f'{X_data_test[i]} - Dự đoán: {prediction} - Kết quả thực: {y_data_test[i]}')

Dự đoán dữ liệu trên test
[0.         0.81578947 0.51219512 0.45945946 0.        ] - Dự đoán: 0 - Kết quả thực: 0
[1.         0.34210526 0.         1.         1.        ] - Dự đoán: 1 - Kết quả thực: 1
[1.         1.         0.57317073 0.27027027 0.84837545] - Dự đoán: 0 - Kết quả thực: 0
[1.         0.         1.         0.37837838 0.47292419] - Dự đoán: 1 - Kết quả thực: 1
[0.         0.63157895 0.79268293 0.         0.07942238] - Dự đoán: 0 - Kết quả thực: 0
